### ISSUE TITLE
ImportError undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by yds5817** [Zhongdao/Towards-Realtime-MOT#12]
```
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from tracker.multitracker import JDETracker
  File "/data/shareJ/YDS/Towards-Realtime-MOT-master/tracker/multitracker.py", line 10, in <module>
    from utils.utils import *
  File "/data/shareJ/YDS/Towards-Realtime-MOT-master/utils/utils.py", line 14, in <module>
    import maskrcnn_benchmark.layers.nms as nms
  File "/data/shareJ/YDS/Towards-Realtime-MOT-master/maskrcnn-benchmark-master/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/data/shareJ/YDS/Towards-Realtime-MOT-master/maskrcnn-benchmark-master/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /data/shareJ/YDS/Towards-Realtime-MOT-master/maskrcnn-benchmark-master/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```
运行时报了这个错。。。

**Comment by Zhongdao** [comment]
This  may attribute to many reasons, do you compile maskrcnn-benchmark with the same environment as used in this code (python version/pytorch version)?

**Comment by yds5817** [comment]
@Zhongdao 谢谢，确实是我的环境有问题。我还有一个问题，就是训练的时候，ccmcpe.json里面的 
这些文件格式是什么样的，我下载的MOT17数据集里面好像没有这些文件。
   ```
"train":
    {
        "mot17":"./data/mot17.train",
        "caltech":"./data/caltech.train",
        "citypersons":"./data/citypersons.train",
        "cuhksysu":"./data/cuhksysu.train",
        "prw":"./data/prw.train",
        "eth":"./data/eth.train"
    },
```

**Comment by yds5817** [comment]
@Zhongdao Thank you so much for your assistance.
