### ISSUE TITLE
Error message No such file or directory: 'weights/run06_04_07_23/cfg/yolo3.cfg'

### ISSUE THREAD

**Issue by josuerocha** [Zhongdao/Towards-Realtime-MOT#129]
Hi @Zhongdao ,

I tried to train the model on Google Colab. However, I always come across the error below. Maybe there is a file that is not being created. I solved it by adding a folder creation routine.

Thanks.

> ================================================================================
dataset summary
OrderedDict([('caltech', 848.0)])
total # identities: 849
start index
OrderedDict([('caltech', 0)])
================================================================================
2020-04-06 07:23:31 [INFO]:    Epoch       Batch       box      conf        id     total  nTargets      time
2020-04-06 07:23:37 [INFO]:     0/29       0/300      0.22      2.05      13.5       129         2      6.89
2020-04-06 07:23:50 [INFO]:     0/29      40/300     0.197      2.04      10.1       111       2.8     0.157
2020-04-06 07:24:03 [INFO]:     0/29      80/300     0.158      1.83      10.8       102      2.81     0.154
2020-04-06 07:24:16 [INFO]:     0/29     120/300     0.129      1.39      10.6      78.6      2.83     0.159
2020-04-06 07:24:29 [INFO]:     0/29     160/300     0.108      1.08      9.58      58.6      2.84     0.152
2020-04-06 07:24:41 [INFO]:     0/29     200/300    0.0936     0.871      8.87      45.4      2.86     0.154
2020-04-06 07:24:54 [INFO]:     0/29     240/300    0.0871     0.732      8.29      36.3      2.86     0.147
2020-04-06 07:25:07 [INFO]:     0/29     280/300    0.0859      0.63      7.84      29.5      2.85     0.146
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    opt=opt,
  File "train.py", line 160, in train
    copyfile(cfg, weights_to + '/cfg/yolo3.cfg')
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'weights/run06_04_07_23/cfg/yolo3.cfg'

**Comment by RENWENKAI** [comment]
Hello, I have the same problem. Have you solved it? How is it solved? Looking forward to reply!

**Comment by MCQCQM** [comment]
the same problem,how to solve it?

**Comment by bigmoking** [comment]
+1

**Comment by kanghu-bo** [comment]
how to solve it?

**Comment by rajatsainju** [comment]
Anyone with any solutions to this?

**Comment by NaifahNurya** [comment]
Please @josuerocha can you share your solution. 

Anyone else who solved this issue. I received the same error.

**Comment by LYZIP** [comment]
> Please @josuerocha can you share your solution.
> 
> Anyone else who solved this issue. I received the same error.


> Hi @Zhongdao ,
> 
> I tried to train the model on Google Colab. However, I always come across the error below. There is a folder that is not being created. I solved it by adding a folder creation routine.
> 
> Thanks.
> 
> > ================================================================================
> > dataset summary
> > OrderedDict([('caltech', 848.0)])
> > total # identities: 849
> > start index
> > OrderedDict([('caltech', 0)])
> > ================================================================================
> > 2020-04-06 07:23:31 [INFO]:    Epoch       Batch       box      conf        id     total  nTargets      time
> > 2020-04-06 07:23:37 [INFO]:     0/29       0/300      0.22      2.05      13.5       129         2      6.89
> > 2020-04-06 07:23:50 [INFO]:     0/29      40/300     0.197      2.04      10.1       111       2.8     0.157
> > 2020-04-06 07:24:03 [INFO]:     0/29      80/300     0.158      1.83      10.8       102      2.81     0.154
> > 2020-04-06 07:24:16 [INFO]:     0/29     120/300     0.129      1.39      10.6      78.6      2.83     0.159
> > 2020-04-06 07:24:29 [INFO]:     0/29     160/300     0.108      1.08      9.58      58.6      2.84     0.152
> > 2020-04-06 07:24:41 [INFO]:     0/29     200/300    0.0936     0.871      8.87      45.4      2.86     0.154
> > 2020-04-06 07:24:54 [INFO]:     0/29     240/300    0.0871     0.732      8.29      36.3      2.86     0.147
> > 2020-04-06 07:25:07 [INFO]:     0/29     280/300    0.0859      0.63      7.84      29.5      2.85     0.146
> > Traceback (most recent call last):
> > File "train.py", line 218, in 
> > opt=opt,
> > File "train.py", line 160, in train
> > copyfile(cfg, weights_to + '/cfg/yolo3.cfg')
> > File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
> > with open(dst, 'wb') as fdst:
> > FileNotFoundError: [Errno 2] No such file or directory: 'weights/run06_04_07_23/cfg/yolo3.cfg'
> 
> In addition, it seems like the test function's signature changed as well:
> 
> > Traceback (most recent call last):
> > File "train.py", line 223, in 
> > opt=opt,
> > File "train.py", line 181, in train
> > print_interval=40, nID=dataset.nID)
> > TypeError: test_emb() got an unexpected keyword argument 'nID'

find 2 lines in train.py
        copyfile(cfg, weights_to + '/cfg/yolo3.cfg')
        copyfile(data_cfg, weights_to + '/cfg/ccmcpe.json')

 , and change as flows. Because the file of weights/cfg is not exist!!
        copyfile(cfg, weights_to + '/cfg_yolo3.cfg')
        copyfile(data_cfg, weights_to + '/cfg_ccmcpe.json')

**Comment by frontseat-astronaut** [comment]
Try specifying config file as parameter --cfg 'config/{config filename}' where config_filename is one of the config files in the config folder

**Comment by mheriyanto** [comment]
Hi @josuerocha , If you got error this

> > Traceback (most recent call last):
> > File "train.py", line 223, in 
> > opt=opt,
> > File "train.py", line 181, in train
> > print_interval=40, nID=dataset.nID)
> > TypeError: test_emb() got an unexpected keyword argument 'nID'

I suggest you to change https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/train.py#L173-L176 script to:

`mAP, R, P = test.test(cfg, data_cfg, weights=latest, batch_size=batch_size, print_interval=20)`

`test.test_emb(cfg, data_cfg, weights=latest, batch_size=batch_size, print_interval=20)  `
