### ISSUE TITLE
TypeError: test() got an unexpected keyword argument 'img_size'

### ISSUE THREAD

**Issue by junjieinkit** [Zhongdao/Towards-Realtime-MOT#147]
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/c9dd7ee438c05ef0ecdc30621a9e9789d417983d/train.py#L175
hello there, an error happens here, did someone know how to fix it?Just delete the unexpected keyword(hier image_size and nID) in the test() function? 
Thanks in advance

**Comment by jwnirvana** [comment]
I miss the same problem，it may run to delete the parameter，but the test input size should influence the inference time

**Comment by jwnirvana** [comment]
There should be a prolem， the img_size show in the table  in reademe could be change. How it does?

**Comment by junjieinkit** [comment]
> There should be a prolem， the img_size show in the table in reademe could be change. How it does?
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/c9dd7ee438c05ef0ecdc30621a9e9789d417983d/train.py#L187
you can change different config file here such as yolov3_1088x608.cfg or yolov3_576x320.cfg in cfg folder or simplely change the image_size (height or width) in one of the .cfg file like 
https://github.com/Zhongdao/Towards-Realtime-MOT/blob/c9dd7ee438c05ef0ecdc30621a9e9789d417983d/cfg/yolov3_1088x608.cfg#L4

**Comment by kanghu-bo** [comment]
how to solve it?

**Comment by NaifahNurya** [comment]
Got the same error at the last iteration of the first epoch after saving trained weight _latest.pt_;  Any update on how to solve this.

_2020-06-10 11:31:24 [INFO]:     0/29   4000/4036       2.3     0.153      4.75      2.73      39.5     0.428
Traceback (most recent call last):
  File "train.py", line 221, in <module>
    opt=opt,
  File "train.py", line 177, in train
    print_interval=40, nID=dataset.nID)
TypeError: test() got an unexpected keyword argument 'img_size'_

**Comment by MrWWY** [comment]
Did you write the correct test data path in your ccmcpe.json file?I have the same problem before,I  solve the problem by writting the correct test data in my ccmpe.json 
like this:
![image](https://user-images.githubusercontent.com/31330418/87917476-a41dff80-caa7-11ea-8465-a6c20d57fc45.png)

**Comment by tcexeexe** [comment]
l meet the same question too,does anyone know how to solve it?
