### ISSUE TITLE
"pip install cython_bbox" always error

### ISSUE THREAD

**Issue by sunxuefeng123** [Zhongdao/Towards-Realtime-MOT#165]
my system is win10, python 3.6, cython was installed. 
log:

(mot) C:\Users\bujingyun>pip install cython_bbox
Collecting cython_bbox
  Using cached cython_bbox-0.1.3.tar.gz (41 kB)
Building wheels for collected packages: cython-bbox
  Building wheel for cython-bbox (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\tool\anaconda\envs\mot\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bujingyun\\AppData\\Local\\Temp\\pip-install-tk9l15e7\\cython-bbox\\setup.py'"'"'; __file__='"'"'C:\\Users\\bujingyun\\AppData\\Local\\Temp\\pip-install-tk9l15e7\\cython-bbox\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\bujingyun\AppData\Local\Temp\pip-wheel-7w02hctf'
       cwd: C:\Users\bujingyun\AppData\Local\Temp\pip-install-tk9l15e7\cython-bbox\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'cython_bbox' extension
  creating build
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\tool\anaconda\envs\mot\lib\site-packages\numpy\core\include -Id:\tool\anaconda\envs\mot\include -Id:\tool\anaconda\envs\mot\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-ID:\Windows Kits\10\include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17763.0\shared" "-ID:\Windows Kits\10\include\10.0.17763.0\um" "-ID:\Windows Kits\10\include\10.0.17763.0\winrt" "-ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcsrc/cython_bbox.c /Fobuild\temp.win-amd64-3.6\Release\src/cython_bbox.obj -Wno-cpp
  cl: 命令行 error D8021 :无效的数值参数“/Wno-cpp”
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for cython-bbox
  Running setup.py clean for cython-bbox
Failed to build cython-bbox
Installing collected packages: cython-bbox
    Running setup.py install for cython-bbox ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\tool\anaconda\envs\mot\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bujingyun\\AppData\\Local\\Temp\\pip-install-tk9l15e7\\cython-bbox\\setup.py'"'"'; __file__='"'"'C:\\Users\\bujingyun\\AppData\\Local\\Temp\\pip-install-tk9l15e7\\cython-bbox\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\bujingyun\AppData\Local\Temp\pip-record-8esbxua6\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\tool\anaconda\envs\mot\Include\cython-bbox'
         cwd: C:\Users\bujingyun\AppData\Local\Temp\pip-install-tk9l15e7\cython-bbox\
    Complete output (11 lines):
    running install
    running build
    running build_ext
    building 'cython_bbox' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\tool\anaconda\envs\mot\lib\site-packages\numpy\core\include -Id:\tool\anaconda\envs\mot\include -Id:\tool\anaconda\envs\mot\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-ID:\Windows Kits\10\include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17763.0\shared" "-ID:\Windows Kits\10\include\10.0.17763.0\um" "-ID:\Windows Kits\10\include\10.0.17763.0\winrt" "-ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcsrc/cython_bbox.c /Fobuild\temp.win-amd64-3.6\Release\src/cython_bbox.obj -Wno-cpp
    cl: 命令行 error D8021 :无效的数值参数“/Wno-cpp”
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\tool\anaconda\envs\mot\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bujingyun\\AppData\\Local\\Temp\\pip-install-tk9l15e7\\cython-bbox\\setup.py'"'"'; __file__='"'"'C:\\Users\\bujingyun\\AppData\\Local\\Temp\\pip-install-tk9l15e7\\cython-bbox\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\bujingyun\AppData\Local\Temp\pip-record-8esbxua6\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\tool\anaconda\envs\mot\Include\cython-bbox' Check the logs for full command output.

**Comment by Deepcong2019** [comment]
首先  pip install cython

**Comment by sunxuefeng123** [comment]
> 首先 pip install cython

cython已经装了的

**Comment by tamamjerbi** [comment]
@sunxuefeng123 You can try to download the package loacally to your pc then edit **setup.py** and  replace 
**extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99']** 
with 
**extra_compile_args={'gcc': ['/Qstd=c99']} in ./libs/datasets/pycocotools/setup.py**
in the setup file and then you can install this package from the local source.

for more on that check this link:
https://stackoverflow.com/questions/60349980/is-there-a-way-to-install-cython-bbox-for-windows

**Comment by fanshu4869** [comment]
download cython_bbox at https://pypi.org/project/cython-bbox/
In setup.py,Changeg extra_compile_args=[’-Wno-cpp’],TO extra_compile_args = {‘gcc’: [’/Qstd=c99’]},
Then, use "python setup.py build_ext install "

**Comment by mahdiabdollahpour** [comment]
> download cython_bbox at https://pypi.org/project/cython-bbox/
> In setup.py,Changeg extra_compile_args=[’-Wno-cpp’],TO extra_compile_args = {‘gcc’: [’/Qstd=c99’]},
> Then, use "python setup.py build_ext install "

did the same and produces Type Error:

running build_ext
building 'cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    keywords = ['cython_bbox']
  File "/home/abdollahpoor/abd_venv/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/abdollahpoor/abd_venv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/abdollahpoor/abd_venv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/abdollahpoor/abd_venv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/abdollahpoor/abd_venv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
TypeError: can only concatenate list (not "dict") to list

**Comment by gioipv** [comment]
I meet same this issue, 
I replace to `extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'],` in `setup.py`. Then run `python setup.py build_ext install`

**Comment by DevindiSiwurathna** [comment]
`pip install -e git+https://github.com/samson-wang/cython_bbox.git#egg=cython-bbox` try this. this solved the issue for me.

**Comment by kishore-work-hard** [comment]
> 

It's not working- 
`running build_ext
D:\vs\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-ID:\Elpark camera test-- kims\pythonProject7\venv\lib\site-packages\nu
mpy\core\include" "-ID:\Elpark camera test-- kims\pythonProject7\venv\include" -IC:\Users\user\AppData\Local\Programs\Python\Python310\include -IC:\Users\user\AppD
ata\Local\Programs\Python\Python310\Include -ID:\vs\VC\Tools\MSVC\14.33.31629\include -ID:\vs\VC\Auxiliary\VS\include /Tcsrc/cython_bbox.c /Fobuild\temp.win-amd64-
3.10\Release\src/cython_bbox.obj -Wno-cpp -Wno-unused-function -std=c99
cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
error: command 'D:\\vs\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
`
