### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by leijuzi** [Zhongdao/Towards-Realtime-MOT#22]
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from tracker.multitracker import JDETracker
  File "/HDD/lq/data/Towards-Realtime-MOT/tracker/multitracker.py", line 10, in <module>
    from utils.utils import *
  File "/HDD/lq/data/Towards-Realtime-MOT/utils/utils.py", line 13, in <module>
    import maskrcnn_benchmark.layers.nms as nms
  File "/HDD/lq/data/Towards-Realtime-MOT/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/HDD/lq/data/Towards-Realtime-MOT/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 5, in <module>
    from apex import amp
  File "/usr/local/lib/python3.6/dist-packages/apex/__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "/usr/local/lib/python3.6/dist-packages/apex/interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "/usr/local/lib/python3.6/dist-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "/usr/lib/python3/dist-packages/zope/interface/declarations.py", line 485, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

**Comment by Zhongdao** [comment]
It seems to be the same problem as #15 
You can try uninstalled the old version of apex and reinstalled a new version.

git clone https://www.github.com/nvidia/apex
cd apex
python setup.py install
