### ISSUE TITLE
AttributeError: 'LoadImages' object has no attribute 'files'

### ISSUE THREAD

**Issue by fanshu4869** [Zhongdao/Towards-Realtime-MOT#223]
Hello, @Zhongdao
first of all, thanks for sharing your work here with us.
I was trying to run track.py as you mentioned in the readme file, and I downloaded the dataset you provided MOT16 but I have this weird error, I'm not sure what is the problem!
I try to run the following:
python track.py --cfg cfg/yolov3_1088x608.cfg --weights weights/jde.1088x608.uncertainty.pt 

and I get this error msg:
2020-06-27 00:21:22 [INFO]: start seq: MOT17-02-SDP
Traceback (most recent call last):
File "track.py", line 215, in
save_videos=opt.save_videos)
File "track.py", line 135, in main
dataloader = datasets.LoadImages(osp.join(data_root, seq, 'img1'), opt.img_size)
File "/home/zc/MOT/jde/utils/datasets.py", line 26, in init
self.nF = len(self.files) # number of image files
AttributeError: 'LoadImages' object has no attribute 'files'
![2021-04-03 21-18-10屏幕截图](https://user-images.githubusercontent.com/57700916/113479585-7e644980-94c2-11eb-8eca-55e47200e454.png)

When I add --test-mot16 to the command line,the results are correct

**Comment by afonseca18** [comment]
Any updates on this issue? 
Thanks in advance.

**Comment by geyu1998** [comment]
you can check whether the path osp.join(data_root,seq,'img1') is true

**Comment by dierye** [comment]
it's a wrong path in the original code: track.py--data_root = os.path.join(opt.data_dir, 'MOT16/train')
you can check this,and add 'images/'
![MT(B82Q``NQLL`)}OHUU1X0](https://user-images.githubusercontent.com/43627503/142556108-7f17c9e2-a165-4da5-822e-73db4b83e7c9.png)

**Comment by JackWoo0831** [comment]
Hello. I've already solved this problem just now. If you're testing it on MOT16, The reason is that you should fix the path in track.py:

Firstly, in line 206, the 'data_root' should be assigned to your own MOT16 dataset test path, e.g.:
`data_root = 'E:/Practice_code/python_code/MOTlearning/deep_sort-master/MOT16/test'`

Secondly, in line 116, the parameter 'data_root' should be assigned to your own MOT16 dataset train path:
`def main(opt, data_root='E:/Practice_code/python_code/MOTlearning/deep_sort-master/MOT16/train', det_root=None, seqs=('MOT16-05',), exp_name='demo', `

Finally, when you run it in terminal, please remember to active the argument '--test-mot16', because it is setted as:
`parser.add_argument('--test-mot16', action='store_true', help='tracking buffer')`
so only when it is actived, the program will test on MOT16.

so the command should be like:
`python track.py --cfg ./cfg/yolov3_1088x608.cfg --weights weights/jde.1088x608.uncertainty.pt --test-mot16`
