### ISSUE TITLE
error in demo.py

### ISSUE THREAD

**Issue by QJC123654** [Zhongdao/Towards-Realtime-MOT#29]
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from tracker.multitracker import JDETracker
  File "/home/fan60526/Towards-Realtime-MOT/tracker/multitracker.py", line 10, in <module>
    from utils.utils import *
  File "/home/fan60526/Towards-Realtime-MOT/utils/utils.py", line 13, in <module>
    import maskrcnn_benchmark.layers.nms as nms
  File "/home/fan60526/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/home/fan60526/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /home/fan60526/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THCudaFree

Hello, I encountered the above error when running demo.py, request to help me solve, I am using python3.7 Cuda version 10.1

**Comment by ThanhPham1987** [comment]
I have an issue like this

**Comment by DANNALI35** [comment]
this error often occurs when you install pytorch with python 3.7, if you are using anaconda env, try the following
 `conda install python=3.6`

**Comment by Zhongdao** [comment]
The main cause of this error is that when you compile pytorch and maskrcnn-benchmark, you use different versions of the compiler, e.g. gcc/nvcc.

I have updated the repo and the codebase does not rely on maskrcnn-benchmark anymore, but you need a newer version of pytorch (>1.2.0).

**Comment by Zhongdao** [comment]
The problem would not occur in the latest version. Please re-open this issue if you still have the same problem.
