### ISSUE TITLE
issue in demo file

### ISSUE THREAD

**Issue by ThanhPham1987** [Zhongdao/Towards-Realtime-MOT#31]
When I run demo.py. I have an issue like this:
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from tracker.multitracker import JDETracker
  File "/home/thanhpham/PycharmProjects/HumanDetection01/venv/MOT/tracker/multitracker.py", line 13, in <module>
    from models import *
  File "/home/thanhpham/PycharmProjects/HumanDetection01/venv/MOT/models.py", line 8, in <module>
    from utilss.syncbn import SyncBN
ImportError: cannot import name 'SyncBN'

******************************************
From the author of paper. I changed the name file utils to utilss my code:
The code of demo.py file

from tracker.multitracker import JDETracker
from utilss import visualization as vis
from utilss.utilss import *
from utilss.io import read_results
from utilss.log import logger
from utilss.timer import Timer
from utilss.evaluation import Evaluator
import utilss.datasets as datasets
import torch
from track import eval_seq
**************************
When run command line:
bash compile.sh to install syncbn
I face issue like this:

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utilss.cpp_extension import CUDAExtension, BuildExtension
ModuleNotFoundError: No module named 'torch'
~/PycharmProjects/HumanDetection01/venv/MOT/utilss/syncbn
Although, I installed torch already.
*****************************

Please give me some advices

**Comment by ThanhPham1987** [comment]
@Zhongdao Can you share information about version cuda, and version pytorch and version ubuntu?

**Comment by Finniu** [comment]
> @Zhongdao Can you share information about version cuda, and version pytorch and version ubuntu?

I applied this model successful before, I use ubuntu 16, cuda 10, pytorch 1.3.
I think if you use conda environment, some isses could be figured

**Comment by Zhongdao** [comment]
@ThanhPham1987 
CUDA 8.0
pytorch 1.0.1
centos 7.5

**Comment by ThanhPham1987** [comment]
@Zhongdao Thank you very much!
