### ISSUE TITLE
demo error!!!

### ISSUE THREAD

**Issue by imnisarg** [Zhongdao/Towards-Realtime-MOT#57]
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    import motmetrics as mm
  File "/home/nisarg/.local/lib/python2.7/site-packages/motmetrics/__init__.py", line 2, in <module>
    from .mot import MOTAccumulator
  File "/home/nisarg/.local/lib/python2.7/site-packages/motmetrics/mot.py", line 12, in <module>
    from motmetrics.lap import linear_sum_assignment
  File "/home/nisarg/.local/lib/python2.7/site-packages/motmetrics/lap.py", line 171, in <module>
    init_standard_solvers()
  File "/home/nisarg/.local/lib/python2.7/site-packages/motmetrics/lap.py", line 149, in init_standard_solvers
    from importlib import util
ImportError: cannot import name util

I am unable to import util even though the importlib is installed in the PC
Please help!!

**Comment by falaktheoptimist** [comment]
Please check if import importlib.util works
