### ISSUE TITLE
I train the model on MOT17 datasets, I met the problem"AssertionError: Caught AssertionError in replica 0 on device 0."

### ISSUE THREAD

**Issue by Happyflytoyou** [Zhongdao/Towards-Realtime-MOT#64]
Traceback (most recent call last):
  File "train.py", line 194, in <module>
    opt=opt,
  File "train.py", line 126, in train
    loss, components = model(imgs.cuda(), targets.cuda(), targets_len.cuda())
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/arena/D/huangw/Project/Towards-Realtime-MOT-master (1)/models.py", line 246, in forward
    x, *losses = module[0](x, self.img_size, targets, self.classifier)
  File "/home/arena/anaconda3/envs/mask_JDE/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/arena/D/huangw/Project/Towards-Realtime-MOT-master (1)/models.py", line 132, in forward
    create_grids(self, img_size, nGh, nGw)
  File "/media/arena/D/huangw/Project/Towards-Realtime-MOT-master (1)/models.py", line 268, in create_grids
    assert self.stride == img_size[1] / nGh
AssertionError

**Comment by Zhongdao** [comment]
Seems the input size is wrong. What is your input image size?
